# CA3

### Imports

In [27]:
# for preprocessing
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# different classifers
from sklearn.linear_model import Perceptron, LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier 


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# for measuring performance
from sklearn.metrics import accuracy_score


# for feature selection
from sklearn.feature_selection import SequentialFeatureSelector

### Reading data

In [39]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
train.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.8,0.610,0.29,1.6,0.114,9.0,29.0,0.99740,3.26,1.56,9.1,0,13
1,8.4,1.035,0.15,6.0,0.073,11.0,54.0,0.99900,3.37,0.49,9.9,0,705
2,8.1,0.290,0.36,2.2,0.048,35.0,53.0,0.99500,3.27,1.01,12.4,1,1408
3,5.2,0.340,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.0,1,144
4,15.6,0.645,0.49,4.2,0.095,10.0,23.0,1.00315,2.92,0.74,11.1,0,557

### Data exploration and visualisation

### Data cleaning

In [38]:
print(train.shape)
print(test.shape)
train = train.dropna()
test = test.dropna()
print(train.shape)
print(test.shape)

print("No rows with missing data")

(835, 13)
(209, 12)
(835, 13)
(209, 12)
No rows with missing data

### Data preprocessing and visualisation

In [ ]:
train = train.sort_values("Id")
test = test.sort_values("Id")

X = train.drop(axis=1, labels=["quality", "Id"])
y = train["quality"]

scaler = StandardScaler()


classifier_types = [Perceptron(), LogisticRegression(), SVC(), DecisionTreeClassifier(), RandomForestClassifier(), KNeighborsClassifier()]
classifiers = []
for classifier in classifier_types:
    if classifier == Perceptron():
        for 
        


for 

for seed in range(100):
    X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = 0.4, random_state=seed)
    X_train_scaled = scaler.fit_transform(X_train)
    X_val_scaled = scaler.transform(X_val)

    for n in range(len(X.keys())):
        for classifier in classifiers:
            sfs = SequentialFeatureSelector(classifier, n_features_to_select=n, direction="forward", n_jobs=4)
            sfs = sfs.fit(X_train_scaled)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
696,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0,0
342,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,0,1
74,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,0,2
14,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0,4
551,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,0,5

### Modelling

In [ ]:
print(len(X.keys()))

### Final evaluation

### Kaggle submission